name: Build Pipeline
run-name: Running build checks
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello World!"
      - run: make format

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests -r requirements.txt

      - name: Run `make format`
        run: make format